apiVersion: apps/v1
kind: Deployment
metadata:
  name: okr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okr
  template:
    metadata:
      labels:
        app: okr
    spec:
      containers:
      - image: okteto.dev/okr:latest
        name: okr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "46836742-50ac-4af0-9bb2-9669e9b35921"
        - name: Vless_Path
          value: "/GHfrk2tijkoe8"
        - name: Vmess_UUID
          value: "46836742-50ac-4af0-9bb2-9669e9b35921"
        - name: Vmess_Path
          value: "/Whlpedyiy30y"
        - name: Share_Path
          value: "/v2link"
